runtime: nodejs18

env_variables:
  # Aquí puedes definir variables de entorno específicas para tu aplicación Node.js, si es necesario.
  # Ejemplo:
  #   MY_ENV_VARIABLE: "mi_valor"

handlers:
- url: /.*
  script: auto

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
